"""remove catalogo_item_id from prescricao_itens

Revision ID: 19a03a7487ff
Revises: ff77f575d7dd
Create Date: 2026-03-24 15:16:51.935212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a03a7487ff'
down_revision = 'ff77f575d7dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescricao_itens', schema=None) as batch_op:
        batch_op.drop_column('catalogo_item_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescricao_itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catalogo_item_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'catalogo_itens', ['catalogo_item_id'], ['id'])

    # ### end Alembic commands ###
