"""Added Configuracao model for PDF header

Revision ID: b679e005ad3c
Revises: 19a03a7487ff
Create Date: 2026-03-24 15:48:48.442961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b679e005ad3c'
down_revision = '19a03a7487ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_empresa', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuracoes')
    # ### end Alembic commands ###
