"""Initial migration

Revision ID: ff77f575d7dd
Revises: 
Create Date: 2026-03-23 13:13:22.416393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff77f575d7dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogo_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao_completa', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descricao_completa')
    )
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('cartao_sus', sa.String(length=20), nullable=True),
    sa.Column('sexo', sa.String(length=1), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('alergias', sa.Text(), nullable=True),
    sa.Column('comorbidades', sa.Text(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cartao_sus')
    )
    op.create_table('internacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('data_internacao', sa.Date(), nullable=False),
    sa.Column('data_saida', sa.Date(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.Column('hipotese_diagnostica', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prescricoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internacao_id', sa.Integer(), nullable=False),
    sa.Column('data_prescricao', sa.Date(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['internacao_id'], ['internacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prescricao_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prescricao_id', sa.Integer(), nullable=False),
    sa.Column('catalogo_item_id', sa.Integer(), nullable=False),
    sa.Column('descricao_foto', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['catalogo_item_id'], ['catalogo_itens.id'], ),
    sa.ForeignKeyConstraint(['prescricao_id'], ['prescricoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prescricao_itens')
    op.drop_table('prescricoes')
    op.drop_table('internacoes')
    op.drop_table('pacientes')
    op.drop_table('catalogo_itens')
    # ### end Alembic commands ###
